### ISSUE TITLE
UnsatisfiedLinkError - Android ZoomVideo SDK

### ISSUE THREAD

**Issue by Android-Lucky** [ajitha-zoom/video-sdk-android#1]
Hi @ajitha-zoom , 

Thank you so much for the Example and detailed explanation.

Am integrating the Video SDK, unfortunately i got below error - I searched in the developer forum but not find any suitable suggestions. Can you please guide me on the same.

java.lang.UnsatisfiedLinkError: No implementation found for void com.zipow.videobox.view.video.VideoRenderer.glRun(int) (tried Java_com_zipow_videobox_view_video_VideoRenderer_glRun and Java_com_zipow_videobox_view_video_VideoRenderer_glRun__I) - is the library loaded, e.g. System.loadLibrary?

I followed the Zoom doucmentation - https://developers.zoom.us/docs/video-sdk/android/integrate/ 

Thank you.

**Comment by ajitha-zoom** [comment]
Hi @Android-Lucky,

I just tried the steps mentioned in the given link and used v1.13.0 to build. Build worked fine. The issue that you mentioned could be pertaining to your environment. 

From the description of the issue, it looks like the dependencies are not loaded/added properly. I am using maven build system. We would need many more details like build system, gradle version to debug further. Also, please raise the query in devforum for getting the right attention: https://devforum.zoom.us/c/video-sdk/android/33

When you raise the query in devforum, please include the build system details, gradle versions, java versions, Android studio version, video sdk version. I am pasting my environment below which worked fine:

Android studio Koala 2024.1.1
Java : v1.8
Maven build system
Zoom Video sdk : v1.13.0
gradle wrapper : gradle-8.7-bin

-Ajitha Yasmin,
Developer Advocate
